### ISSUE TITLE
Comma missing

### ISSUE THREAD

**Issue by johnjohndoe** [teikei/teikei#114]
There is a comma missing in the "So funktioniert's" info box on the start page:

> ... Wie genau sich der Ernteanteil zusammensetzt hängt von der Jahreszeit und dem Angebot des Betriebs ab.

Fixed here:

> ... Wie genau sich der Ernteanteil zusammensetzt, hängt von der Jahreszeit und dem Angebot des Betriebs ab.

**Comment by zonque** [comment]
On 06/24/2015 01:16 AM, Tobias Preuss wrote:
> There is a comma missing in the "So funktioniert's" info box on the
> start page:
> 
>     ... Wie genau sich der Ernteanteil zusammensetzt hängt von der
>     Jahreszeit und dem Angebot des Betriebs ab.
> 
> Fixed here:
> 
>     ... Wie genau sich der Ernteanteil zusammensetzt, hängt von der
>     Jahreszeit und dem Angebot des Betriebs ab.

This text is now stored in a TextBlock and can be edited easily in the
admin frontend. Fixed :)

**Comment by johnjohndoe** [comment]
Thank you.
