### ISSUE TITLE
Update deployment chain

### ISSUE THREAD

**Issue by johnjohndoe** [teikei/teikei#117]
I noticed that a bunch of people continued working on [*uberspacify*](https://github.com/johnjohndoe/uberspacify). None of them sent a pull request though. It might be worth checking what people did and incorporate their changes in order to update *uberspacify*. The original author seems to no longer maintain it.

* [johnjohndoe/uberspacify - network](https://github.com/johnjohndoe/uberspacify/network)
* [johnjohndoe/uberspacify - stargazers](http://forked.yannick.io/johnjohndoe/uberspacify)

**Comment by cnrk** [comment]
Uberspacify is no longer maintained and only works with Capistrano 2. 

We updated the deployment process by replacing uberspacify with capistrano-uberspace [1]. This then allowed us to update to Capistrano 3. capistrano-uberspace is a newer, Capistrano 3-compatible gem inspired by uberspacify. Works like a charm. :ok_hand:

[1] https://github.com/tessi/capistrano-uberspace

**Comment by johnjohndoe** [comment]
Sounds good. Just for completeness I like to mention [fhemberger/uberspace-deployment](https://github.com/fhemberger/uberspace-deployment) and to notify @fhemberger ..
