### ISSUE TITLE
Move place creation wizard into a separate component.

### ISSUE THREAD

**Issue by sjockers** [teikei/teikei#140]
Currently, the wizard for creating places is a very clunky backbone component. It never worked really good and is the reason for a lot of issues with old dependencies like backbone-forms.

By replacing this with a react/redux based component we could get rid of a lot backbone related dependencies. This may finally allow us to migrate from NPM 2 to NPM 3 (needs verification).

**Comment by cnrk** [comment]
:thumbsup:
