### ISSUE TITLE
Add single sign-on feature

### ISSUE THREAD

**Issue by zonque** [teikei/teikei#15]
Some links:

* http://ux.stackexchange.com/questions/26035/why-do-sites-with-a-single-sign-on-system-redirect-to-a-login-screen
* http://ux.stackexchange.com/questions/78/whats-more-user-friendly-local-authentication-or-remote-authentication-openid?rq=1
* http://stackoverflow.com/questions/5013716/single-sign-on-across-many-domain-without-cookies

**Comment by cnrk** [comment]
not an issue anymore.
