### ISSUE TITLE
restrict geocoding/search to current country

### ISSUE THREAD

**Issue by cnrk** [teikei/teikei#166]
should the search really be restricted to the currently selected country? or is this too confusing for the user? also, should it just show places of the currently selected country or all places? 

how does the geocoder behave when adding an entry? should it also be restricted to just one country? 

maybe it's more intuitive to always show results from all supported countries (CH/DE)

**Comment by sjockers** [comment]
> should the search really be restricted to the currently selected country? or is this too confusing for the user?

Very good point. If it is easy, we should go with searching in both countries for now. 

> also, should it just show places of the currently selected country or all places?

We should always show all places.

> how does the geocoder behave when adding an entry? should it also be restricted to just one country? maybe it's more intuitive to always show results from all supported countries (CH/DE)

Yes, let's go with both countries for now.

**Comment by cnrk** [comment]
Restricting search to multiple countries is currently not possible, we could use a bounding box that comes close however though:

<img width="480" alt="bounding_box_tool__metadata_enrichment_for_catalogue_records_by_visually_selecting_geographic_coordinates__latitude___longitude__for_maps" src="https://cloud.githubusercontent.com/assets/976303/24083489/e1b0da84-0cd7-11e7-95ab-df3a2f683bf9.png">

**Comment by sjockers** [comment]
Ok, let's go for this.
