### ISSUE TITLE
Improved geocoder

### ISSUE THREAD

**Issue by sjockers** [teikei/teikei#188]
Apparently, results are subpar, especially for Switzerland. 

> Bei ortoloco z.B. erscheint der falsche Ort. Die Spreitenbacherstrasse 35 und der Betrieb ortoloco liegen in Dietikon, angezeigt wird Zürich (http://www.solawi.ch/vernetzungsplattform/#/farms/550).

> Die Adresse von Bioco ist "Geisshof, 5412 Gebenstorf". Wurde nicht gefunden, alternativ dazu habe ich nun die Geisslistrasse als Adresse eingegeben. (http://www.solawi.ch/vernetzungsplattform/#/farms/521)

Ideas: Add fuzzy search, switch to a different geocoding service (Mapbox, Here Maps)

-> test with mapbox geocoder

**Comment by crijke** [comment]
we switched to HereMaps now, which solves the cases describes above and should improve results in general.
