### ISSUE TITLE
API provides phone number only to authenticated users

### ISSUE THREAD

**Issue by sjockers** [teikei/teikei#201]
*Steps to reproduce:*

`https://ernte-teilen.org/api/v1/farms/333` 

ownerships[0].phone is undefined

*To fix:*

Phone number should be provided

**Comment by crijke** [comment]
This is actually a feature™️, but I don't remember why it was implemented like that, as it don't see a possible use case. 

The API also has 'contact_by_phone' and 'contact_by_email' flags for each ownership, but we no longer use them apparently. I will remove them as well. 

As a result, phone number will always be shown, also to anonymous users.

**Comment by crijke** [comment]
We decided to not include this information in the API at all.
