### ISSUE TITLE
API seems to be missing some fields for farms

### ISSUE THREAD

**Issue by tantebootsy** [teikei/teikei#204]
It seems like the json from the API is missing the following fields which I think are not critical to distribute (in regard of privacy):

1.  founded_at_year
2. founded_at_month
3. maximum_members
4. products_additional_information
5. acts_ecological
6. economical_behavior
7. participation

Would be nice to have them available with the new API.

**Comment by crijke** [comment]
These fields have been made available in the meantime and are now part of the API.
