### ISSUE TITLE
Website redesign

### ISSUE THREAD

**Issue by sjockers** [teikei/teikei#30]
![2014-05-07_home](https://cloud.githubusercontent.com/assets/449739/3112175/504091c8-e6bc-11e3-9ddf-9f229e6701a6.png)

---

![2014-05-07_map](https://cloud.githubusercontent.com/assets/449739/3112178/591e04ce-e6bc-11e3-859e-1986d7caec5c.png)

This is a major task and should probably be broken apart into separate issues. 

---

Possible sub-task (ordered by priority):

- ~~Implement marker clustering using [Leaflet.Markercluster](https://github.com/Leaflet/Leaflet.markercluster)~~ – extracted to #45.
- ~~Replace typekit font-embed with [Fira](https://github.com/mozilla/Fira) font family, installed via bower~~ – extracted to #48 
- ~~Update general styling of map (see design comps above)~~ 
- ~~Use responsive design techniques to make the map work on mobile devices (to be specified)~~ – #3, #68, #69 
- Implement homepage as a separate rails view (see design comps above)

**Comment by johnjohndoe** [comment]
WOW. Excited. Tension builds up in me!

**Comment by cnrk** [comment]
check it out: https://ernte-teilen.org/  :boom: :sparkles: :tada: :tada:

**Comment by johnjohndoe** [comment]
Awesome. Prost :wine_glass: :beers:

**Comment by zonque** [comment]
:+1: \o/

**Comment by johnjohndoe** [comment]
Uff. That was a lot of work I guess. Please enter your working here: ___
