### ISSUE TITLE
Auto-generated API documentation

### ISSUE THREAD

**Issue by johnjohndoe** [teikei/teikei#34]
There should be a auto-generated API documentation. The following tools might be helpful ...
- [Grape](https://github.com/intridea/grape) for the API
- [Swagger UI](https://github.com/wordnik/swagger-ui) for the user interface
- [grape-swagger](https://github.com/tim-vandecasteele/grape-swagger) as a middleware

**Comment by crijke** [comment]
We should introduce a RAML specification with JSON schemas at some point to generate the docs (and to have more nice things, like validation).

**Comment by crijke** [comment]
we will track this in taiga now: https://tree.taiga.io/project/sjockers-teikeinext
