### ISSUE TITLE
Add search function

### ISSUE THREAD

**Issue by zonque** [teikei/teikei#5]
Add a search function to the frontend.

**Comment by cnrk** [comment]
- one search field with 'fuzzy matching' e.g. fragment of an address, city, postcodes etc
- when an adress is entered, suggestions are shown incrementally based on a location search (e.g. 30 km around the location)
- if a suggestions is selected, the map zooms to the selected entry
- if none is selected, the map zooms to the actual position

**Comment by cnrk** [comment]
- [ ] combine place search and geocoding lookup on server and expose as single endpoint
- [ ] use new endpoint in search component
- [ ] limit geocoding results to DACH region
- [ ] change display of search results to include less detail (for example just the name of the city and country and not the state, district etc)
- [ ] update UI: 
  - [ ] align search box with 'add entry' buttons
  - [ ] increase size of search box, improve background of search box
  - [ ] search results should have fixed width

**Comment by sjockers** [comment]
I just found out about [open cage](https://geocoder.opencagedata.com/demo), a new geocoding service that looks very promising. I ran a couple of random tests with addresses in rural areas and got very good results, even including German postal codes (Nominatim has issues with that) and place names that are not street addresses (try searching for "Gutshof Neuruppin" or "Korker Mühle"). 

Open cage has a free tier for up to 2500 requests per day. That may be enough if we throttle geocoder requests. What do you think?

**Comment by cnrk** [comment]
Very interesting. OpenCage combines multiple geocoding systems, including Nominatim. And it has an easy way to restrict geocoding to a country or specific bounds.

There doesn't seem to be support for structured queries though. Which may not be an issue, as their unstructured queries seem to deliver better results than our current queries. So I'd give it a try.

**Comment by sjockers** [comment]
We decided on using the [Mapzen geocoder](https://mapzen.com/products/search/) via https://github.com/alexreisner/geocoder

**Comment by johnjohndoe** [comment]
:rocket: Very nice!!!
