### ISSUE TITLE
Hide network does not work

### ISSUE THREAD

**Issue by johnjohndoe** [teikei/teikei#56]
When a network is shown the user **cannot hide the network** by simply **clicking onto the map base layer**. The screenshot shows the state of the map when this happens.

![network](https://cloud.githubusercontent.com/assets/144518/3536642/3d4dded0-0814-11e4-92d7-0304f5f79be0.png)

This happens when the pop-up window of a place disappears after clicking on the button which shows the network.

**Comment by sjockers** [comment]
We have removed the network view because it does not work for clustered marker layers. See #83 for updates.

**Comment by johnjohndoe** [comment]
Too bad. One of the nice features. But hopefully it will be back soon.
