### ISSUE TITLE
Introduce number interval validator

### ISSUE THREAD

**Issue by johnjohndoe** [teikei/teikei#58]
There seems to be room for improvement regarding the `function validateNumber(min, max)` used [here](https://github.com/teikei/teikei/blob/master/app/assets/javascripts/apps/places/views/entry_farm.js#L35). Please have a look at [this post](http://stackoverflow.com/a/24757134/356895) - it might be worth changing the implementation for the sake of the DRY principle.

**Comment by cnrk** [comment]
All of this code has been replaced during our rewrite of the frontend.
