### ISSUE TITLE
Add changelog, roadmap

### ISSUE THREAD

**Issue by johnjohndoe** [teikei/teikei#72]
Now that the project is **in production** I like to encourage you to maintain a **changelog**. Further, a **roadmap** to outline what comes next would be awesome.
There are plenty of examples out there - here are some links that might interest you:
- [Healthy Hacker - Open source checklist](http://www.healthyhacker.com/2014/08/25/open-source-checklist/) (Audio)
- [TypedPreferences CHANGELOG](https://github.com/johnjohndoe/TypedPreferences/blob/master/CHANGELOG.md)
- [Umweltzone CHANGELOG](https://bitbucket.org/tbsprs/umweltzone/src/587e553eb5b93d7ffa25fe749dc7d8ae4c6ce64f/CHANGELOG.md?at=master)
- [Guard releases](https://github.com/guard/guard/releases)
- [ActiveAdmin CHANGELOG](https://github.com/activeadmin/activeadmin/blob/master/CHANGELOG.md)
- [Jamine Goals](https://github.com/jasmine/jasmine/blob/master/GOALS_2.0.md)

What about version 1.0.0 by the way?

**Comment by sjockers** [comment]
We decided to add a roadmap to the project readme, see this issue on Taiga for details: https://tree.taiga.io/project/sjockers-teikeinext/issue/105

We will not maintain a changelog for now as we deploy continuously without formal releases.
